### ISSUE TITLE
Newsletter update

### ISSUE THREAD

**Issue by richgilbank** [nodeschool/toronto#42]
Re: https://github.com/nodeschool/newsletter/issues/8

Anyone have something that could go toward writing up a little blurb on our happenings? We've been one of the most active NodeSchools that I know of, would be great to share a bit about our process and events. 

@nodeschool/toronto-mentors

**Comment by Rchristiani** [comment]
### Nodeschool Toronto

![Nodeschool TO](http://nodeschool.io/toronto/i/photos/15.jpg)

2015 saw the beginning of Nodeschool Toronto. Our goal at the start was to provide an event every month. Besides a small summer break, we have hit this mark! It's been amazing to see the group grow in size with each event.

We've started to experiment with new ideas. For example, the team introduced lightning talks at the beginning of the event. In these talks mentors discuss topics like debugging in node, new features in ES6, and electron. 

![](http://nodeschool.io/toronto/i/photos/27.jpg)

The mentors are not the only people presenting talks, attendees who have been working on something they are proud of are encouraged to demo their project! Communication is also key to keeping things moving, the Toronto chapter slack has been a great way for mentors and attendees to keep in touch.

In 2016 we are looking to keep the momentum going, creating a safe space for attendees to learn and have fun!

**Comment by chrismendis** [comment]
@Rchristiani thanks for putting this together! I have a few of suggestions for how to break up the first paragraph's ideas in to two separate paragraphs in order to improve clarity:

2015 saw the beginning of Nodeschool Toronto. ~~Since~~ **Our goal at the start** ~~we have been trying~~ **was** to provide an event every month~~,~~**.** ~~b~~**B**esides a small summer break, we have hit this mark! ~~Each event grows and new ideas are experimented with.~~ **It's been amazing to see the group grow in size with each event.**

**We've started to experiment with new ideas. For example,** ~~T~~**t**he team introduced lightning talks at the beginning of the event. In these talks mentors discuss topics like debugging in node, new features in ES6, and electron.

**Comment by Rchristiani** [comment]
@chrismendis updated the post.

**Comment by chrismendis** [comment]
:+1:

**Comment by darcyclarke** [comment]
:+1:

**Comment by ahmadnassri** [comment]
LGTM

**Comment by richgilbank** [comment]
:shipit:

**Comment by andrewdamelio** [comment]
:ship: :it:

**Comment by darcyclarke** [comment]
I gotta start photoshoppin' myself in some of these photos lol

**Comment by Rchristiani** [comment]
I think we just need a camera with tripod! Get everyone in!
